name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test
        run: ./mvn clean package
      - name: Build Docker image
        run: |
          docker build -t spring-boot-docker.jar .
          docker tag spring-boot-docker my-docker-registry/spring-boot-docker

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker