name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build and test
        run: mvn clean install
      - name: Build Docker image
        run: |
          docker build -t spring-boot-docker . --tag ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker